version: '3'
services:

    blog:
        build: .
        image: paskal/hugo

        logging:
          driver: json-file
          options:
            max-size: "10m"
            max-file: "5"

        volumes:
            - ./public:/srv/hugo/public
            - ./:/srv/hugo:ro

    blog-preview:
        image: paskal/hugo
        command: -D --bind "0.0.0.0" server
        hostname: blog-preview
        container_name: blog-preview

        logging:
          driver: json-file
          options:
            max-size: "10m"
            max-file: "5"

        ports:
            - "1313:1313"

        volumes:
            - ./:/srv/hugo:ro

    cv:
        build: ./cv
        image: paskal/jsonresume
        command: export --theme kendall /tmp/verhoturov.html

        logging:
          driver: json-file
          options:
            max-size: "10m"
            max-file: "5"

        volumes:
            - ./public/cv/:/tmp/
            - ./cv/resume.json:/data/resume.json:ro

    pdf:
        image: pink33n/html-to-pdf
        command: --url https://terrty.net/cv/verhoturov.html --pdf verhoturov.pdf
        privileged: true

        logging:
          driver: json-file
          options:
            max-size: "10m"
            max-file: "5"

        volumes:
            - ./public/cv:/tmp/html-to-pdf
