version: '3'
services:

    blog:
        build: .
        image: paskal/hugo

        logging:
          driver: json-file
          options:
            max-size: "10m"
            max-file: "5"

        volumes:
            - ./public:/srv/hugo/public
            - ./:/srv/hugo

    blog-preview:
        image: paskal/hugo
        command: -DF --bind "0.0.0.0" server

        logging:
          driver: json-file
          options:
            max-size: "10m"
            max-file: "5"

        ports:
            - "1313:1313"

        volumes:
            - ./:/srv/hugo

